trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - manifests/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

pr: none

stages:
- stage: build
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      name: "DAS - Continuous Integration"
      demands:
      - docker
    steps:
      - task: UseGitVersion@5
        inputs:
          versionSpec: 5.x
          useConfigFile: true
          configFilePath: GitVersion.yml

      - task: Docker@2
        displayName: Build Image
        inputs:
          command: build
          dockerfile: Dockerfile
          repository: apprenticeshipsdevops/das-tools-support
          tags: $(build.buildnumber)
          arguments: --no-cache

      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: "Apprenticeships DevOps Docker Hub"

      - task: Docker@2
        displayName: Push Image
        inputs:
          command: push
          repository: apprenticeshipsdevops/das-tools-support
          tags: $(build.buildnumber)

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          contents: |
            azure/**
            manifests/**
          targetFolder: '$(build.artifactstagingdirectory)/publish'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          pathtoPublish: '$(build.artifactstagingdirectory)/publish'
