trigger:
  batch: false
  branches:
    include:
      - "*"
  paths:
    include:
      - azure/*
      - src/*
      - pipeline-templates/*
      - azure-pipelines.yml

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.6
    endpoint: GitHub (SFA)
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.2.9
    endpoint: GitHub (SFA)

pr:
  - master

variables:
- group: RELEASE Management Resources
- group: Wildcard Cert Variables v2
- group: RELEASE das-tools-support

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-tools-support
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        CommitmentsClientApiConfigurationClientSecret: $(CommitmentsClientApiConfigurationClientSecret)
        AccountClientApiConfigurationClientSecret: $(AccountClientApiConfigurationClientSecret)
        EmployerUserClientApiConfigurationClientSecret: $(EmployerUserClientApiConfigurationClientSecret)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/SFA.DAS.Tools.Support.Web.zip

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-tools-support
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        CommitmentsClientApiConfigurationClientSecret: $(CommitmentsClientApiConfigurationClientSecret)
        AccountClientApiConfigurationClientSecret: $(AccountClientApiConfigurationClientSecret)
        EmployerUserClientApiConfigurationClientSecret: $(EmployerUserClientApiConfigurationClientSecret)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/SFA.DAS.Tools.Support.Web.zip

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: PREPROD Management Resources
  - group: PREPROD Shared Resources
  - group: PREPROD das-tools-support
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-PreProd-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        CommitmentsClientApiConfigurationClientSecret: $(CommitmentsClientApiConfigurationClientSecret)
        AccountClientApiConfigurationClientSecret: $(AccountClientApiConfigurationClientSecret)
        EmployerUserClientApiConfigurationClientSecret: $(EmployerUserClientApiConfigurationClientSecret)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DIG-PreProd-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/SFA.DAS.Tools.Support.Web.zip

- stage: Deploy_PROD
  dependsOn: Build
  displayName: Deploy to PROD
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: PROD Management Resources
  - group: PROD Shared Resources
  - group: PROD das-tools-support
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: PROD
      TemplatePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        CommitmentsClientApiConfigurationClientSecret: $(CommitmentsClientApiConfigurationClientSecret)
        AccountClientApiConfigurationClientSecret: $(AccountClientApiConfigurationClientSecret)
        EmployerUserClientApiConfigurationClientSecret: $(EmployerUserClientApiConfigurationClientSecret)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: PROD
      ServiceConnection: SFA-DIG-Prod-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/SFA.DAS.Tools.Support.Web.zip

- stage: Deploy_MO
  dependsOn: Build
  displayName: Deploy to MO
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: MO Management Resources
  - group: MO Shared Resources
  - group: MO das-tools-support
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: MO
      TemplatePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        CommitmentsClientApiConfigurationClientSecret: $(CommitmentsClientApiConfigurationClientSecret)
        AccountClientApiConfigurationClientSecret: $(AccountClientApiConfigurationClientSecret)
        EmployerUserClientApiConfigurationClientSecret: $(EmployerUserClientApiConfigurationClientSecret)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: MO
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/SFA.DAS.Tools.Support.Web.zip
