trigger:
  batch: true
  branches:
    include:
      - QUAL-643-DirectAADLogin
  paths:
    include:
      - azure/*
      - src/*
      - pipeline-templates/*
      - azure-pipelines.yml

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.2.6
    endpoint: GitHub (SFA)

pr: none

variables:
- group: Release Management Resources
- group: Wildcard Cert Variables v2

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-tools-support (temp)
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        CommitmentsClientApiConfigurationClientSecret: $(CommitmentsClientApiConfigurationClientSecret)
        AzureAdConfigurationClientSecret: $(AzureAdConfigurationClientSecret)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM      
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/SFA.DAS.Tools.Support.Web.zip