parameters:
  Environment:  
  AppRoleAssignmentsServiceConnection:
  Tenant:

jobs:
- deployment: ApplyAppRoleAssignments
  dependsOn: DeployInfrastructure
  variables:
    AppServiceName: $[dependencies.DeployInfrastructure.outputs['DeployInfrastructure.ArmOutputs.AppServiceName']]
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: $(AppServiceName)
            Tenant: ${{ parameters.Tenant }}