parameters:  
  DeploymentApprovals:
  ServiceConnection:
  DeploymentPackagePath:

jobs:
- deployment: DeployWebApp
  dependsOn: DeployInfrastructure  
  variables:
    ResourceGroupName: $[dependencies.DeployInfrastructure.outputs['DeployInfrastructure.ArmOutputs.ResourceGroupName']]
  environment: ${{ parameters.DeploymentApprovals }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $[dependencies.DeployInfrastructure.outputs['DeployInfrastructure.ArmOutputs.AppServiceName']]
            DeploymentPackagePath: ${{ parameters.DeploymentPackagePath }}