---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: das-self-service-web
  namespace: {{Namespace}}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{IngressHost}}`) && PathPrefix(`/support`)
      kind: Rule
      middlewares:
        - name: secured
      services:
        - name: das-self-service
          port: 80
          healthCheck:
            path: /support/health
            host: {{IngressHost}}
            intervalSeconds: 7
            timeoutSeconds: 60
  tls:
    secretName: '{{TlsSecretName}}-correct-chain'
    options:
      name: enforce-tls-12
      namespace: {{Namespace}}
