---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: das-tools-support-portal
    service: das-tool-service
  name: das-tools-support-portal
  namespace: {{Namespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: das-tools-support-portal
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: das-tools-support-portal
    service: das-tool-service
  name: das-tools-support-portal
  namespace: {{Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: das-tools-support-portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: das-tools-support-portal
        service: das-tool-service
    spec:
      containers:
      - env:
        - name: VstsConfig__CollectionUri
          value: {{CollectionUri}}
        - name: VstsConfig__ProjectName
          value: {{ProjectName}}
        - name: VstsConfig__PatToken
          value: {{PatToken}}
        - name: VstsConfig__RequiredRole
          value: {{RequiredRole}}
        image: {{WebImage}}
        imagePullPolicy: IfNotPresent
        name: das-tools-support-portal
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 512Mi
        volumeMounts:
          - mountPath: /app/appsettings.json
            name: shared-app-settings
            subPath: appsettings.json
      volumes:
        - name: shared-app-settings
          configMap:
            name: das-tool-service-shared-config
