---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: das-tools-support
    service: das-tool-service
  name: das-tools-support
  namespace: {{Namespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: das-tools-support
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: das-tools-support
    service: das-tool-service
  name: das-tools-support
  namespace: {{Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: das-tools-support
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: das-tools-support
        service: das-tool-service
    spec:
      containers:
      - env:
        - name: RequiredRole
          value: {{RequiredRole}}
        - name: CommitmentsClientApiConfiguration__ClientId
          value: {{CommitmentsClientApiConfigurationClientId}}
        - name: CommitmentsClientApiConfiguration__ClientSecret
          value: {{CommitmentsClientApiConfigurationClientSecret}}
        - name: CommitmentsClientApiConfiguration__ApiBaseUrl
          value: {{CommitmentsClientApiConfigurationApiBaseUrl}}
        - name: CommitmentsClientApiConfiguration__IdentifierUri
          value: {{CommitmentsClientApiConfigurationIdentifierUri}}
        - name: CommitmentsClientApiConfiguration__Tenant
          value: {{CommitmentsClientApiConfigurationTenant}}
        image: {{WebImage}}
        imagePullPolicy: IfNotPresent
        name: das-tools-support-portal
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 512Mi
        envFrom:
          - configMapRef:
              name: das-tool-service-shared-config
      volumes:
        - name: shared-app-settings
          configMap:
            name: das-tool-service-shared-config
