<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SFA.DAS.Account.Api.Client" Version="1.6.3195" />
    <PackageReference Include="SFA.DAS.CommitmentsV2.Api.Client" Version="8.29.1" />
    <PackageReference Include="SFA.DAS.Encoding" Version="1.1.76" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="System.Text.Json" Version="10.0.9" /> 
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="MediatR" Version="[12.5.0]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.Tools.Support.Core\SFA.DAS.Tools.Support.Core.csproj" />
  </ItemGroup>

</Project>
